### ISSUE TITLE
Loading contacts in group doesn't always work

### ISSUE THREAD

**Issue by adriaon** [mozillahispano/openwapp#158] opened 2015-08-13 11:59 UTC
Often, in a group, the loading of the contacts never completes. There is just the message 'Loading contacts...' and posts list a phone number in stead of a name.

**Comment by Timmaks** [comment] 2015-08-13 18:02
Thankz for reporting this issue but this is a dupe of #132

**Closed by Timmaks** 2015-08-13 18:02 UTC
