### ISSUE TITLE
Message not received, no icon

### ISSUE THREAD

**Issue by feklee** [mozillahispano/openwapp#108] opened 2015-03-26 13:57 UTC
Last night I sent a message, and the recipient did not receive it. She, however, received the messages before and after that. Curiously, associated with the message is no icon. Seeing that there is no icon, I restarted the phone, and reconnected with OpenWapp, making sure it is online, but to no avail: The icon was still missing.

![Edited screenshot, showing no icon for message](https://cloud.githubusercontent.com/assets/14994/6847586/9d79ddbe-d3bf-11e4-9726-4dcf630515b5.png)

rev: 1.7.4-0-ge417a1a
OS: Boot2Gecko 1.3.0.0-prerelease
Device: Geeksphone Keon

**Comment by bobcanthelpyou** [comment] 2015-07-22 22:25
The "no icon" problem is a duplicate of #11

**Comment by Timmaks** [comment] 2015-11-09 09:56
Can you check if this is still a issue in the current version?

**Comment by feklee** [comment] 2015-11-09 10:01
Hard to tell because the issue appeared randomly, maybe only once, and I don't use WhatsApp anymore.

**Comment by Timmaks** [comment] 2015-11-09 10:04
ok thanks, closing. Please reopen when anyone sees this issue again

**Closed by Timmaks** 2015-11-09 10:04 UTC
Labels: bug
