### ISSUE TITLE
I NEED UR HELP

### ISSUE THREAD

**Issue by Mrkamilo5** [mozillahispano/openwapp#86] opened 2015-01-14 02:09 UTC
Hi, my name is Cristian, I'm from Colombia and I had a problem with my cellphone, a ZTE Open II and for those reason a had to reset the phone, time before i wanted to install this app but now appears a message like this, and i don't know what i have to do, ok, My mobile operator is Movistar Colombia and my e-mail is: kamcriz@hotmail.com or my number is +573188707853. please HELP ME I NEED USE WHATSAPP :) 
![2015-01-08-10-02-23](https://cloud.githubusercontent.com/assets/8303406/5732914/1a83823a-9b60-11e4-94a6-3a3f7e3ea7f6.png)

**Comment by willyaranda** [comment] 2015-01-14 10:19
Dupe of https://github.com/mozillahispano/openwapp/issues/61

**Closed** 2015-01-14 10:19 UTC
