### ISSUE TITLE
No cell routes for sending sms caused by your operator

### ISSUE THREAD

**Issue by inpu** [mozillahispano/openwapp#88] opened 2015-01-26 13:12 UTC
This message i can see when trying to Sign-up. I already have used OpenWapp on Mozilla Flame. Now i just reinstall app and can not Signup.
And one more bug, when i choose country, i select Russian Federation and there posted code +79, but Russian Federation country code is +7, but not +79.
See here: http://en.wikipedia.org/wiki/Telephone_numbers_in_Russia
This was earlier too, but it works fine. A see arrived sms with codes.
Maybe because after +7 i have 9 in my phone number, so +79 is correct for me, but not for other people.

I use Mozilla Flame.
os: 2.1.0.0-prerelease

**Comment by willyaranda** [comment] 2015-01-26 14:35
duplicate of #61

**Closed by willyaranda** 2015-01-26 14:35 UTC
Labels: duplicate

**Comment by inpu** [comment] 2015-01-28 18:46
After update all my problems are gone! Thanks a lot ;)
