### ISSUE TITLE
Unable to download video/picture

### ISSUE THREAD

**Issue by MARUTHIADITHYA** [mozillahispano/openwapp#79] opened 2014-12-25 02:57 UTC
Finally i got Openwapp working in my phone....but now i am not able to download the pictures and videos sent.

**Comment by Timmaks** [comment] 2015-11-10 08:41
Does this issue still exist in the current version?

**Comment by telefrancisco** [comment] 2015-11-11 23:17
For me the problem is solved.

**Comment by Timmaks** [comment] 2015-11-12 09:30
Great, closing.

**Closed by Timmaks** 2015-11-12 09:30 UTC
Labels: bug, confirmed, P1
