### ISSUE TITLE
can only receive messages posted into groups

### ISSUE THREAD

**Issue by MartinSauer** [mozillahispano/openwapp#171] opened 2015-11-09 14:45 UTC
I installed the new version1.9.2. But now I can only receive messages posted into groups. Messages from single users don´t reach me. Tested with different users using originla WA on android.
Sending is all fine.

(FFOS 2.2. on Open C)

Greetings, Martin

**Comment by cmeerw** [comment] 2015-11-09 21:44
If you happen to have an Android phone with WhatsApp handy, could you send a test message to +447961596923 please?

**Comment by Timmaks** [comment] 2015-11-09 21:51
Just send

**Comment by Timmaks** [comment] 2015-11-09 21:53
Have blue ticks so whatsapp tells me you read it...

**Comment by cmeerw** [comment] 2015-11-09 22:31
Thanks a lot @Timmaks - it looks like I might have a fix for this issue. Essentially, we need to reply with an error when receiving an encrypted message and then get the plaintext message delivered.

**Comment by Timmaks** [comment] 2015-11-10 08:30
Great news, looking forward to the PR :)

**Comment by cmeerw** [comment] 2015-11-18 18:05
Please see loqui/im#882 for the coseme changes that have been implemented in Loqui.

**Comment by jesobreira** [comment] 2015-11-22 03:43
I can confirm the same problem on Firefox OS 1.1 (LG Fireweb) with latest OpenWapp version as of today (just downloaded it).

**Comment by Timmaks** [comment] 2015-11-23 08:05
this should be fixed in the new version 1.9.4, please reopen if you still see this problem

**Closed by Timmaks** 2015-11-23 08:05 UTC
