### ISSUE TITLE
New registration ended with `undefined´

### ISSUE THREAD

**Issue by MartinSauer** [mozillahispano/openwapp#168] opened 2015-11-05 16:38 UTC
latest OpenWapp on Firefox Aurora (2.2).
I typed in the code sent via SMS from WA and received a message "OpenWapp, undefined" on a black Screen. The code was ok. On original WA on my second mobile the registration succeeded.

**Comment by jssCAT** [comment] 2015-11-07 01:20
Hi,

I think that the problem is the same that this one:
https://github.com/mozillahispano/openwapp/issues/169

When I tried to reinstall the app, it wasn't possible to use the app with the code sent via SMS.

For the moment, it seems that it's not possible to connect to the network. If you want, you can take a look to the different messages that will be published here, in the "Issues" section, during these days. Probably will appear a notification when the problem will be solved.

Greetings.

**Comment by Timmaks** [comment] 2015-11-07 20:41
This would be fixed with version 1.9.2, if not please reopen

**Closed by Timmaks** 2015-11-07 20:41 UTC

**Comment by Timmaks** [comment] 2015-11-08 11:13
New version is now aviable in Marketplace

**Comment by MartinSauer** [comment] 2015-11-09 14:40
Thanks,

I installed the new version. But now I can only receive messages posted 
into groups. Messages from single users don´t reach me. Tested with 
different users using originla WA on android.
Sending is all fine.

Viele Grüße,
Martin Sauer

Am 08.11.2015 um 12:13 schrieb T.M. van den Broek:
