### ISSUE TITLE
Please add plural forms

### ISSUE THREAD

**Issue by bidaian** [mozillahispano/openwapp#192] opened 2016-01-01 08:20 UTC
There are two pretty frequent strings:

"You have {{count}} new messages."

and

"From {{count}} conversations."

that are gramatically incorrect, at least in Spanish, Portuguese and Dutch when count=1. Esperanto tries to cover both count = 1 and count != 1 but the result is not visually pleasing. And, again, that text is shown a lot, often with count = 1.

Could you add the plural forms? Gaia solves this like this (newVoicemails):

https://hg.mozilla.org/releases/gaia-l10n/v2_2/en-US/file/default/apps/system/system.properties#l91

I think that for OpenWapp [one] and [many] might be enough.

**Comment by Timmaks** [comment] 2016-01-01 09:09
Dupe of #137

**Closed by Timmaks** 2016-01-01 09:09 UTC
