### ISSUE TITLE
Running in simulator result in white screen

### ISSUE THREAD

**Issue by Timmaks** [mozillahispano/openwapp#84] opened 2015-01-03 09:38 UTC
Steps

-clone git rep
-sudo npm install
-sudo gem install bundler && bundle install
-bower install
-grunt
-open webIDE
-open packege app
-point to openwapp/dist/
-start simulator
-push openwapp to simulator

result
-simulator ask for permissions, Allow
-white screen

log
10:35:27.436 "[background service] Started" background-service.js:26
10:35:27.667 "[background service] Next awake signal with id" 17 "by" "Sat Jan 03 2015 10:40:27 GMT+0100 (CET)" background-service.js:88
10:35:27.900 "Possible sim cards" Array [  ] login.js:173
10:35:27.903 " *** currentView has been cleared" router.js:212

Is there a way to bypass the login in the simulator and test the UI with the fake contacts?

**Comment by duesenfranz** [comment] 2015-01-03 12:22
Thanks for the report, can reproduce with FFOS 2.0.

Just a Tipp: The simulator sometimes disregards some console logs (and error messages), caused by the debugger starting too late. This can be resolved by 
* Starting the app
* Pressing the debugger button
* Restarting the app. The debugger is now active all the time.

Also this time, this prints ``TypeError: this.template is not a function`` at ``login.js:94``.

Comparing to a local version I already head, there is this difference in ``app/scripts/templates.js``:
    < return this["Handlebars"];
    ---
    > return this["Handlebars"]["templates"];

In grunt-contrib-handlebars, they mention that they [fixed amd namespacing](https://github.com/gruntjs/grunt-contrib-handlebars/commit/03c0679212f72f24c2b1fbc8daba060b5cdde77f).



------------------
Unfortunately, starting the app with fake contacts does not work. This would probably require mocking the whole WA backend :/

**Comment by duesenfranz** [comment] 2015-01-03 12:43
I *think* it works now..
@Timmaks can you check with ``git@github.com:duesenfranz/openwapp.git``? :sunny: (my bower doesn't like me :/)
@willyaranda since they only talk about *namespace functions*... Is this a bug on our- or on their end?

**Comment by Timmaks** [comment] 2015-01-03 13:16
@duesenfranz yes you have fixed it! Thanks!

how do you test the chnages you make if you can't get pasted the registration screen in the simulator?  I don't have to send messages but i want to see the different screen to check on translations etc.

**Closed** 2015-01-03 13:17 UTC
Labels: bug, confirmed

**Comment by duesenfranz** [comment] 2015-01-03 13:24
Personally, I use a version on my phone that I build on my computer. This means I can make a change, repush, and continue usage normally.

Again, usage with fake messages is hard. However, upon loading, the app goes initally to the ``inbox`` view. There it tries to authenticate, and **if that fails**, it goes to the ``login`` view. So you could try stopping this rerouting behavour. Note that other errors may occur, but I don't know anything better. :/

To do this, you could temporarily delete/outcomment [these lines](https://github.com/mozillahispano/openwapp/blob/f479108c59f30ad09133206ef0c1628ced9b0109/app/scripts/views/inbox.js#L42-L47)

**Comment by Timmaks** [comment] 2015-01-04 15:58
@duesenfranz thanks.  Comment out those lines is enough to do the test i want :-)
