### ISSUE TITLE
Older groups are not loaded when signing in OpenWapp

### ISSUE THREAD

**Issue by oteo** [mozillahispano/openwapp#127] opened 2015-06-12 14:03 UTC
STR:
1. Install OpenWapp
2. Sign-in with a Misisdn that already had some groups chats opened in whatsapp/openwapp application

Current Result: the chat list is completely empty
Expected Result: Older group chats should be showed in the chat Inbox

Note: This was working in older versions of the application

**Comment by Timmaks** [comment] 2015-06-12 14:32
please provide more details. witch version of openwapp/fxos/phone/..

**Comment by oteo** [comment] 2015-06-12 14:39
FxOS: latest master version (today's build 12 Jun 2015)
OpenWapp: 1.7.6 (latest available in the MP)
Device:Flame

**Comment by Timmaks** [comment] 2015-06-12 18:48
Are you seeing that there are no groups or that the groups you are member to are there but empty?

**Comment by oteo** [comment] 2015-06-12 20:47
There are not any groups and they should be there. 

I was expecting that they were empty as you mention but I can not check that as there are not any group chat

**Comment by willyaranda** [comment] 2015-06-13 12:15
It may be possible that WA has switched off groups v1 and there are using the v2. And we don't have any code for that.

**Comment by naitsirch** [comment] 2015-06-21 22:03
Same problem here. The progress bar is rotating endlessly.
In console log it says:
> "[history] Syncing groups..." history.js:258
> DataError: Data provided to an operation does not meet requirements. dbmanager.js:586:0

It looks like `IDBKeyRange.only` does not accept `null` values. So I have changed 

```javascript
if (value !== undefined) {
```
in line 585 to
```javascript
if (value !== undefined && value !== null) {
```
Now my console log says:
> "[history] Syncing groups..." history.js:258
> "[history] Loading conversation:" null history.js:230
> "[history] Conversation:" null "not found." history.js:243
> TypeError: this.get(...) is null conversation.js:48:0
> "[contacts] Loading contact" null "from storage." contacts.js:78

Coseme gets a conversation, but with `gid === null`and empty subject.

I am using current OpenWapp 1.7.x build, device ZTE Open C with FOS version 1.3

**Comment by Himra** [comment] 2015-10-26 12:52
I have the same Problem on OpenWapp 1.8.x build, device ZTE Open C with FOS version 2.2

**Comment by Timmaks** [comment] 2015-11-07 20:43
This is fixed in the current version

**Closed by Timmaks** 2015-11-07 20:43 UTC

**Comment by naitsirch** [comment] 2015-11-08 19:25
confirmed. Thanks!
