### ISSUE TITLE
Can't register on nightly

### ISSUE THREAD

**Issue by Hywan** [mozillahispano/openwapp#118] opened 2015-05-01 11:37 UTC
Hello :-),

New update of Firefox OS nightly (3.0) today. Opening OpenApp. I am prompted to register this phone (why? it was working yesterday ;-)) and when I enter my phone number waiting for the SMS, I have the following error:

> Old version, please contact OpenWapp devs.

Here I am :-).

**Comment by Airon90** [comment] 2015-05-01 12:32
This error happens to me, too!

**Comment by Insurrectionist** [comment] 2015-05-01 13:30
Something similar happened to me but on 1.3. It was working then around an hour later it prompted to register my phone.

**Comment by holztest08** [comment] 2015-05-01 13:46
The same problem. I think WhatsApp changed something with the client requirements...

**Comment by eduardoandre** [comment] 2015-05-01 14:45
I need the old version please!

**Comment by eduardoandre** [comment] 2015-05-01 14:48
I am brazilian, I don't speak english. But I need the old version, please. Because my app this not working.

Thank you very very much

**Comment by nebocamin** [comment] 2015-05-01 16:24
Can confirm on three phones. Yesterday it was working today, not anymore. Me on 2.2 and on 2.0 same effect. Maybe "they" changed something.

**Comment by ChrAck** [comment] 2015-05-01 18:08
Yes, same behaviour in Germany/Congstar:  Old version message and non working client; seems to be a general change in authentication... :-/

**Comment by alex-mayorga** [comment] 2015-05-01 18:12
Just another "me too" on Flame 2.2...

If only my contacts would ditch WhatsApp and evolve into Telegram =(

**Comment by willyaranda** [comment] 2015-05-01 18:47
I had a PR on CoSeMe (the underlying library to connect to WA) by @titannano

https://github.com/mozillahispano/coseme/pull/15

Merged. I will create a new zip and upload to the store ASAP.

**Comment by willyaranda** [comment] 2015-05-01 19:00
I have generated a new version with just this change,

could someone test? I don't have any FirefoxOS phone until Monday.

https://cloud.pijusmagnificus.com/index.php/s/xP29bddXqAoPyS2

Thanks!!

**Comment by Shadow1g** [comment] 2015-05-01 19:24
tested --> 1.7.5.0 doesnt work

**Comment by Insurrectionist** [comment] 2015-05-01 20:15
Tested it too, not solved on Firefox OS 1.3.

**Comment by nebocamin** [comment] 2015-05-01 20:20
works for me, using 2.2 on a flame

**Comment by holztest08** [comment] 2015-05-01 22:24
Still the same error. Loqui also have the same problem...yowsup works.

**Comment by Airon90** [comment] 2015-05-02 01:26
@willyaranda I tested it on my Flame under Firefox OS 3.0 (latest update: 30th April) but the problem still occurs

**Comment by ChrAck** [comment] 2015-05-02 08:38
Works fine for me too:  2.0 on Alcatel 6015x

**Comment by TitanNano** [comment] 2015-05-02 13:53
hello, everyone here is talking of the device registration not the authentication of an already set up account?

@willyaranda on Loqui we got a report from a failed code request where whatsapp respondes with "bad_token". The token is assembled by CoSeMe from the phone number and a static string like this 
`var plain = 'PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1418865329241' + phone;`
maybe we need to update this static string? If so how can we get the new version?

**Comment by aesedepece** [comment] 2015-05-02 14:13
The new string should be ```PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1425519315543{phone}```.

**Comment by TitanNano** [comment] 2015-05-02 14:14
@aesedepece I see I'll create a pull request for CoSeMe and Loqui. How do you get the string?

**Comment by aesedepece** [comment] 2015-05-02 14:18
It needs to be extracted from official app's package. That one came from WhatsApp 2.12.68 for S40.

**Comment by TitanNano** [comment] 2015-05-02 14:24
I see, thank you for providing it +1. I patched Loqui so we need to wait
for people to test if it's possible to register again. If so I'll do a PR
for CoSeMe too.

2015-05-02 16:18 GMT+02:00 Adán Sánchez de Pedro Crespo <
notifications@github.com>:

**Comment by tchetch** [comment] 2015-05-02 14:43
I had the same problem and changing the string did correct it ... I could register.

**Comment by TitanNano** [comment] 2015-05-02 14:44
@tchetch alright. thanks for the test :) I'll do a PR for CoSeMe.

**Comment by feklee** [comment] 2015-05-02 18:27
Downloaded the zip from my device, unzipped it, changed the code to `PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1425519315543`, zipped again, and copied it to my device. Last steps:

    $ zip -r ../application.zip *
    $ cd ..
    $ sudo adb push application.zip /data/local/webapps/{ce5ca96f-8384-488f-b100-ec1c6b780da7}

Then I restarted my Keon (1.3), and still I am requested to enter my PIN, which I do *not* get by SMS. Coincidentally, the problem exists since yesterday. Still, I guess it's unrelated to what has been reported here. I do *not* get the *"Old version, please contact OpenWapp devs."* error message.

**Comment by tchetch** [comment] 2015-05-02 18:34
I used the zip from @willyaranda on FirefoxOS 1.3.0.0 on a ZTE Open C

**Comment by Shadow1g** [comment] 2015-05-02 19:19
"PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1425519315543" works fine!

**Comment by feklee** [comment] 2015-05-02 21:09
@tchetch Cool, the zip by @willyaranda works. I see that there are a couple of other strings / version numbers updated.

**Comment by Andreas-Berger** [comment] 2015-05-03 12:51
Hi!
Just wanted to let you know workaround (unzip / change string / zip) described by feklee works for me too. Using Firefox 2.0 on geeksphone revolution - Thanks!!!

**Comment by feklee** [comment] 2015-05-03 13:01
Possibly I didn't have the latest version installed.

@Andreas-Berger The string is in `webapps.json`, as describe in the wiki page on [migration][1].

[1]: https://github.com/mozillahispano/openwapp/wiki/Migration

**Comment by Hywan** [comment] 2015-05-04 05:58
The recent update did not fix it :-(.

**Comment by willyaranda** [comment] 2015-05-04 10:21
I just pushed a new version to the marketplace (1.7.6). Waiting to be approved.

**Comment by Shadow1g** [comment] 2015-05-04 10:58
sure? there is still the 1.7.5 online

**Comment by Hywan** [comment] 2015-05-04 11:25
@willyaranda Perfect. Let's wait and see :-).

**Comment by willyaranda** [comment] 2015-05-04 13:49
Approved. Please update and report :) Thanks!

**Closed by willyaranda** 2015-05-04 13:49 UTC

**Comment by pmquste** [comment] 2015-05-04 14:10
Preciso de ajuda!! MMeu openwapp não está funcionando desde a semana passada. Eu o utiizava para trabalho e atender meus clientes. Tento registrar meu telefone mas dá a seguinte mensagem "Indefinido". O que devo fazer...Lí as instruçoes de vocês nesse forum mas não consigo entender o que significa e onde colocar todos esses códigos....

**Comment by pmquste** [comment] 2015-05-04 14:39
i need help! Cant install the openwapp on my firefox since last week. Is says "Indefined". Any help please.

**Comment by Insurrectionist** [comment] 2015-05-04 19:35
Working on ZTE Open II - Firefox OS 1.3.

**Comment by trompetix** [comment] 2015-05-04 20:01
thank you willyaranda! 
I just reinstalled your new verision: great job!
Works for me on Alcatel OneTounch Fire E with FFOS 2.0.0 01009B

**Comment by willyaranda** [comment] 2015-05-04 20:14
Great! Huge thanks to @aesedepece  and @TitanNano

**Comment by khepriduat** [comment] 2015-05-04 22:18
Solved! Now working on ZTE Open with 2.0. Thanks!

**Comment by Hywan** [comment] 2015-05-05 07:42
Solved on nightly. Great job :-).

**Comment by Shadow1g** [comment] 2015-05-05 11:33
The problem isn solved, it works only for some hours, after this you lose the connection to the WA-network. All you can do after that is to reinstall openwapp. thats no permanent solution...

**Comment by Hywan** [comment] 2015-05-05 12:12
@Shadow1g Hmm, I can't reproduce your issue. What is your version of Firefox OS (because some of them have troubles with the socket API).

**Comment by Shadow1g** [comment] 2015-05-05 12:34
Firefox OS 2.0 // Alcatel One Touch Fire E

**Comment by Airon90** [comment] 2015-07-16 22:57
Again I was disconnected to Whatsapp and when I tried to ask a code for my phone number OpenWapp warned me that the version is obsolete but there isn't any new version of OpenWapp. :(

**Comment by Timmaks** [comment] 2015-07-17 07:12
This is a closed issue so please open a new issue (it is new because it is a result of a chnage in whatsapp) like the somebody did in issue #144 .

**Comment by Hywan** [comment] 2015-07-17 09:41
@Airon90 Same here…
