### ISSUE TITLE
New version problem

### ISSUE THREAD

**Issue by capsnew** [mozillahispano/openwapp#145] opened 2015-07-17 07:04 UTC
I use OpenWapp on my fxOS device and I have this message when I'm trying to change my phone number (I need to because I changed my SIM card): 'Old version, please contact OpenWapp devs'. I already uninstalled & re-installed app from the Marketplace, it doesn't work better.

**Comment by Timmaks** [comment] 2015-07-17 07:13
dupe of #144

**Closed by Timmaks** 2015-07-17 07:13 UTC
