### ISSUE TITLE
Unable to delete/clear conversations.

### ISSUE THREAD

**Issue by Insurrectionist** [mozillahispano/openwapp#95] opened 2015-02-18 20:25 UTC
Whenever the history of a conversation is really long and with a lot of messages it takes a long time to send a new message. Also the message duplicates. Deleting the conversation does nothing because the history is not deleted, when you open the conversation it shows all the messages. In order to clear it all, you have to delete each message one by one. 

I'm not sure if it's the same issue as #68.

**Comment by bobcanthelpyou** [comment] 2015-07-22 22:10
@Insurrectionist could you still reproduce this issue with the latest v1.8.1 release?

**Comment by Timmaks** [comment] 2015-11-10 08:39
Closing because no answer from the reporter, please reopen if you still see this issue

**Closed by Timmaks** 2015-11-10 08:39 UTC
